[package]
name = "gl-matrix4rust"
description = "gl-matrix port version for Rust"
authors = ["MagicCrazyMan <350088648@qq.com>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
